hedera:
  mirror:
    restJava:
      db:
        host: 127.0.0.1
        name: mirror_node
        password: mirror_rest_java_pass
        port: 5432
        sslMode: DISABLE
        statementTimeout: 10000
        username: mirror_rest_java
      response:
        headers:
          defaults:
            # Headers set by default unless overridden in specific request mapping paths defined below.
            "Access-Control-Allow-Origin": "*"
            "Cache-Control": "public, max-age=1"
          path:
            # Override inherited defaults and define additional headers for individual controller request mappings.
            # "[]" around the path preserves special characters. Multiple header name/value pairs may be defined per path.
            "[/api/v1/topics/{id}]":
              "Cache-Control": "public, max-age=5"

    grpc:
      listener:
        type: SHARED_POLL
    importer:
      startDate: 1970-01-01T00:00:00.000Z
      parser:
        record:
          entity:
            persist:
              transactionBytes: false
              transactionRecordBytes: false
              transactionHash: true
            redis:
              enabled: false
          sidecar:
            enabled: true
      downloader:
        accessKey: minioadmin
        cloudProvider: S3
        secretKey: minioadmin
        bucketName: hedera-streams
        endpointOverride: http://minio:9000
      initialAddressBook: /usr/etc/hedera-mirror-importer/local-dev-1-node.addressbook.f102.json.bin
      network: OTHER
    monitor:
      mirrorNode:
        grpc:
          host: mirror-node-grpc
          port: 5600
        rest:
          host: mirror-node-rest
          port: 5551
      publish:
        scenarios:
          pinger:
            properties:
              amount: 1
              maxTransactionFee: 10000
              senderAccountId: 0.0.2
              recipientAccountId: 0.0.55
              transferTypes:
                - CRYPTO
            receiptPercent: 1
            tps: 10
            type: CRYPTO_TRANSFER
      subscribe:
        grpc:
          hcs:
            enabled: false
        rest:
          transactionId:
            enabled: true
            samplePercent: 1
      network: OTHER
      nodes:
        - accountId: 0.0.3
          host: network-node
      operator:
        accountId: 0.0.2
        privateKey: 302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137
    web3:
      opcode:
        tracer:
          enabled: true
