{
 "title": "Block-Node Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mediator Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hedera_block_node_live_block_stream_mediator_error_total",
       "legendFormat": "Block Item Errors"
      }
     ]
    },
    {
     "title": "Rate of Mediator Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hedera_block_node_live_block_stream_mediator_error_total [$__rate_interval])",
       "legendFormat": "Mediator Errors"
      }
     ]
    },
    {
     "title": "Stream Persistence Errors",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hedera_block_node_stream_persistence_handler_error_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Stream Persistence Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(hedera_block_node_stream_persistence_handler_error_total [$__rate_interval])",
       "legendFormat": "Stream Persistence Errors"
      }
     ]
    }
   ]
  },
  { "title": "Live Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Live Block Items Received from Producer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_live_block_items_received_total",
     "legendFormat": "BlockItems"
    }
   ]
  },
  {
   "title": "Rate of Live Block Items Received from Producer",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate( hedera_block_node_live_block_items_received_total [$__rate_interval])",
     "legendFormat": "BlockItems"
    }
   ]
  },
  {
   "title": "Live Block Item Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_live_block_items_total",
     "legendFormat": "BlockItems"
    }
   ]
  },
  {
   "title": "Rate of Live Block Items Received by Mediator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate( hedera_block_node_live_block_items_total [$__rate_interval])",
     "legendFormat": "BlockItems"
    }
   ]
  },
  {
   "title": "Live Block Items Consumed Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_live_block_items_consumed_total",
     "legendFormat": "BlockItems Consumed"
    }
   ]
  },
  {
   "title": "Rate of Block Items Sent to Consumer(s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate( hedera_block_node_live_block_items_consumed_total [$__rate_interval])",
     "legendFormat": "BlockItems"
    }
   ]
  },
  {
   "title": "Mediator Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_mediator_ring_buffer_remaining_capacity",
     "legendFormat": "Mediator Remaining Capacity"
    }
   ]
  },
  {
   "title": "Mediator Ring Buffer Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "min(hedera_block_node_mediator_ring_buffer_remaining_capacity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifier Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_notifier_ring_buffer_remaining_capacity",
     "legendFormat": "Notifier Remaining Capacity"
    }
   ]
  },
  {
   "title": "Notifier Ring Buffer Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "min(hedera_block_node_notifier_ring_buffer_remaining_capacity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hedera_block_node_producers", "legendFormat": "Producers" }
   ]
  },
  {
   "title": "Consumers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hedera_block_node_consumers", "legendFormat": "Consumers" }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Block Persistence Counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_blocks_persisted_total",
     "legendFormat": "Block Persistence Counter"
    }
   ]
  },
  {
   "title": "Rate of Blocks Written to the File System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(hedera_block_node_blocks_persisted_total[$__rate_interval])",
     "legendFormat": "Block Persistence Counter"
    }
   ]
  },
  { "title": "Live Stream Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "PublishStreamResponses Generated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_successful_pub_stream_resp_total",
     "legendFormat": "PublishStreamResponses"
    }
   ]
  },
  {
   "title": "Rate of PublishStreamResponses Generated",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate( hedera_block_node_successful_pub_stream_resp_total [$__rate_interval])",
     "legendFormat": "PublishStreamResponses"
    }
   ]
  },
  {
   "title": "PublishStreamResponses Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_successful_pub_stream_resp_sent_total",
     "legendFormat": "PublishStreamResponses"
    }
   ]
  },
  {
   "title": "Rate of PublishStreamResponses Sent to Producers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hedera_block_node_successful_pub_stream_resp_sent_total[$__rate_interval])",
     "legendFormat": "PublishStreamResponses"
    }
   ]
  },
  { "title": "Single Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Single Blocks Retrieved",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_single_blocks_retrieved_total",
     "legendFormat": "Single Blocks Retrieved"
    }
   ]
  },
  {
   "title": "Rate of Single Blocks Retrieved",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hedera_block_node_single_blocks_retrieved_total[$__rate_interval])",
     "legendFormat": "RPS of Single Blocks Retrieval"
    }
   ]
  },
  {
   "title": "Single Blocks Not Found",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedera_block_node_single_blocks_not_found_total",
     "legendFormat": "Single Blocks Not Found"
    }
   ]
  },
  {
   "title": "Rate of Single Blocks Not Found",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate( hedera_block_node_single_blocks_not_found_total [$__rate_interval])",
     "legendFormat": "Single Blocks Not Found"
    }
   ]
  }
 ]
}