global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'development'
    static_configs:
    - targets: [ '172.27.0.3:9999' ]
      labels:
        environment: 'local'
        node_id: "0"
  - job_name: 'relay-development'
    scrape_interval: 15s
    static_configs:
    - targets: [ 'json-rpc-relay:7546' ]
      labels:
        cluster: 'local'
        namespace: 'local'        
