datasources:
- name: local-prom
  access: proxy
  type: prometheus
  url: http://172.27.0.4:9090
  isDefault: true

- name: Prometheus
  type: prometheus
  uid: PBFA97CFB590B2093
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: true
  jsonData:
    timeInterval: 1s
