name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  publish-npm-package:
    runs-on: local-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js 20.x
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean install
        run: npm ci

      - name: Publish npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
