name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  publish-npm-package:
    runs-on: local-node-linux-medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Node.js 20.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean install
        run: npm ci

      - name: Publish npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
