name: Smoke Tests
on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        network: [mainnet, testnet, local, previewnet]

    name: ${{ matrix.network }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          cd test/smoke
          npm ci

      - name: Start the local node with ${{ matrix.network }} images
        run: node cli.js start --network ${{ matrix.network }} -d

      - name: Run smoke test
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 3
          command: npm run test:smoke

      - name: Stop the local node
        run: node cli.js stop
